### ISSUE TITLE
X-success parameter not working when logging a date

### ISSUE THREAD

**Issue by redpot** [Letterboxd/letterboxd-ios-x-callback-url#1]
When I make a call to log a review that x-success parameter doesn’t seem to work if I include the date parameter. However if exclude the date I can then create a review, save it in letterboxd which triggers the x-success property.

**Comment by redpot** [comment]
For example this doesn’t trigger x-success:
letterboxd://x-callback-url/log?name=Knockabout&date=2018-01-29&x-success={{launch:}}
Whereas this does:
letterboxd://x-callback-url/log?name=Knockabout&x-success={{launch:}}

**Comment by ryanmaxwell** [comment]
@redpot thanks for the bug report. I've found the fault and it will be fixed in our next release!
